### ISSUE TITLE
Arming issue

### ISSUE THREAD

**Issue by AradhyaSpace11** [monemati/multiuav-gazebo-simulation#1]
in the mav console

AP: PreArm: Main loop slow (271Hz < 400Hz)
AP: PreArm: Main loop slow (272Hz < 400Hz)
Flight battery 100 percent
AP: PreArm: Main loop slow (272Hz < 400Hz)
AP: PreArm: Main loop slow (272Hz < 400Hz)
Flight battery 100 percent
AP: PreArm: Main loop slow (272Hz < 400Hz)

**Comment by monemati** [comment]
@AradhyaSpace11 Hi. This error usually indicated that the simulator is not getting enough resources such as CPU. You can start with only 1 drone to see if it is running ok or not. As a workaround you can disable the arming check by typing >> param set ARMING_CHECK 0 in the first terminal like below:
param set ARMING_CHECK 0
mode guided
arm throttle
takeoff 5

**Comment by AradhyaSpace11** [comment]
Thank You so much for the quick response. I tried your solution and it worked as intended. I have been searching for a proper simulator tool for beginners and almost all of the documentations are too technical, which I believe helps if the users are experts but it does confuse newcomers. Thank you so much for providing concise documentation. My team appreciates the effort a lot

**Comment by monemati** [comment]
@AradhyaSpace11 Your welcome <3

**Comment by AradhyaSpace11** [comment]
Thank You for the quick reply to the other issue as well
