### ISSUE TITLE
How do I program the drone using python?

### ISSUE THREAD

**Issue by ghost** [monemati/multiuav-gazebo-simulation#2]
.

**Comment by monemati** [comment]
@Aradhya2711 You can use [pymavlink](https://github.com/ArduPilot/pymavlink) instead of dronekit.

**Comment by ghost** [comment]
wonderful. i did just that. Also, I can see that whenever I run rostopic list in my terminal, the rostopic 

~/iris/iris_demo/gimbal_small_2d/tilt_link/camera/image

is not listed. researching into it i understood that its a private rostopic, i tried to input this rostopic instead of the one the uav camera python code in your repository has, however, after multiple tries running the script you provided I am not getting any image feed

any solutions to this?

**Comment by ghost** [comment]
also, when I press ctrl + T and see the camera view within gazebo, the image is inverted. what can be a possible solution within gazebo itself

**Comment by monemati** [comment]
> wonderful. i did just that. Also, I can see that whenever I run rostopic list in my terminal, the rostopic
> 
> ~/iris/iris_demo/gimbal_small_2d/tilt_link/camera/image
> 
> is not listed. researching into it i understood that its a private rostopic, i tried to input this rostopic instead of the one the uav camera python code in your repository has, however, after multiple tries running the script you provided I am not getting any image feed
> 
> any solutions to this?

You can change the topic name in "Publish UAV's camera feed on ROS topic" part (model.sdf):
```
           <cameraName>uav1/camera1</cameraName>
           <imageTopicName>image_raw</imageTopicName>
           <cameraInfoTopicName>camera_info</cameraInfoTopicName>
```

**Comment by monemati** [comment]
> also, when I press ctrl + T and see the camera view within gazebo, the image is inverted. what can be a possible solution within gazebo itself

You can just change uav_camera.py line #25 from this:

`resized_image = cv2.resize(image, (640, 640)) `

to this:

```
# Flip the image horizontally
flipped_image = cv2.flip(cv_image,  1)
resized_image = cv2.resize(flipped_image, (640,  640))  
```
